services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      DATABASE_URL: "postgres://admin:admin@db/apinodedb"
    command: "npm run dev"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 1000M

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "apinodedb"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 1000M

volumes:
  postgres-data:
